//
//  //
//  AISourceBadge.swift
//  Aptus
//
//  Small badge that shows which AI generated the content the user is reading.
//  Apple Intelligence (on-device) or Template (deterministic).
//  Tapping the badge opens a short explanation with privacy details.
//

import SwiftUI

struct AISourceBadge: View {
    let source: NarrativeInsight.Source

    @State private var showingInfo = false

    var body: some View {
        Button {
            showingInfo = true
        } label: {
            HStack(spacing: 4) {
                Image(systemName: iconName)
                    .font(.caption2)
                Text(shortLabel)
                    .font(.caption2)
                    .fontWeight(.semibold)
            }
            .padding(.horizontal, 8)
            .padding(.vertical, 4)
            .background(tint.opacity(0.15))
            .foregroundColor(tint)
            .clipShape(Capsule())
            .overlay(
                Capsule().stroke(tint.opacity(0.35), lineWidth: 0.5)
            )
        }
        .buttonStyle(.plain)
        .accessibilityLabel("Generated by \(shortLabel). Tap for details.")
        .sheet(isPresented: $showingInfo) {
            AISourceInfoSheet(source: source)
        }
    }

    private var iconName: String {
        switch source {
        case .appleIntelligence: return "sparkles"
        case .gemini:            return "text.alignleft"
        case .template:          return "text.alignleft"
        }
    }

    private var shortLabel: String {
        switch source {
        case .appleIntelligence: return "Apple Intelligence"
        case .gemini:            return "On-device"
        case .template:          return "On-device"
        }
    }

    private var tint: Color {
        switch source {
        case .appleIntelligence: return .purple
        case .gemini:            return .secondary
        case .template:          return .secondary
        }
    }
}

// MARK: - Info Sheet

private struct AISourceInfoSheet: View {
    let source: NarrativeInsight.Source
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    header

                    Divider()

                    Text(explanation)
                        .font(.subheadline)
                        .foregroundColor(.secondary)

                    Divider()

                    VStack(alignment: .leading, spacing: 8) {
                        Label("How Aptus chooses", systemImage: "gearshape")
                            .font(.headline)
                        Text("Aptus automatically uses Apple Intelligence on devices that support it (iOS 26+ on Apple-Intelligence-capable hardware). On older devices, or if on-device generation is unavailable, Aptus fills in a deterministic on-device template. You don't need to configure anything.")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                    }

                    Divider()

                    VStack(alignment: .leading, spacing: 8) {
                        Label("Privacy", systemImage: "lock.shield")
                            .font(.headline)
                        Text("Apple Intelligence runs entirely on your device — nothing leaves your phone. Your health data is never sold, shared, or sent to third parties.")
                            .font(.subheadline)
                            .foregroundColor(.secondary)
                    }

                    Divider()

                    HStack(alignment: .top, spacing: 8) {
                        Image(systemName: "exclamationmark.shield")
                            .foregroundColor(.secondary)
                        Text("Informational wellness estimates only — not a diagnosis or medical device.")
                            .font(.footnote)
                            .foregroundColor(.secondary)
                    }
                }
                .padding()
            }
            .navigationTitle("About this insight")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }
            }
        }
    }

    private var header: some View {
        HStack(spacing: 12) {
            Image(systemName: iconName)
                .font(.title)
                .foregroundColor(tint)
                .frame(width: 44, height: 44)
                .background(tint.opacity(0.15))
                .clipShape(Circle())
            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .font(.headline)
                Text(subtitle)
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            Spacer()
        }
    }

    private var iconName: String {
        switch source {
        case .appleIntelligence: return "sparkles"
        case .gemini:            return "text.alignleft"
        case .template:          return "text.alignleft"
        }
    }

    private var tint: Color {
        switch source {
        case .appleIntelligence: return .purple
        case .gemini:            return .secondary
        case .template:          return .secondary
        }
    }

    private var title: String {
        switch source {
        case .appleIntelligence: return "Apple Intelligence"
        case .gemini:            return "On-device template"
        case .template:          return "On-device template"
        }
    }

    private var subtitle: String {
        switch source {
        case .appleIntelligence: return "On-device · private"
        case .gemini:            return "Deterministic · no AI used"
        case .template:          return "Deterministic · no AI used"
        }
    }

    private var explanation: String {
        switch source {
        case .appleIntelligence:
            return "This insight was written by Apple Intelligence, Apple's on-device large-language model. Generation happens entirely on your iPhone's Neural Engine — no data is sent over the network for this response."
        case .gemini:
            return "Apple Intelligence wasn't available for this insight, so Aptus filled in a deterministic on-device template based on your metrics. It's not written by AI — just structured text — but it always reflects your latest data."
        case .template:
            return "Apple Intelligence wasn't available for this insight, so Aptus filled in a deterministic on-device template based on your metrics. It's not written by AI — just structured text — but it always reflects your latest data."
        }
    }
}
//

